import { id, list, now, table } from "../state/store.js";
export const protectedProfileDomains = ["personal_memory", "preferences", "health_wellness", "pet_care", "vehicle_information", "business_context"];
const profiles = () => table("profiles"); const grants = () => table("profile_grants"); const audit = () => table("access_audit");
export function bootstrapOwner(bootstrapToken) { if (!bootstrapToken?.trim()) throw Object.assign(new Error("Local development bootstrap token is required."), { status: 503 }); if (!profiles().has("owner")) profiles().set("owner", { id: "owner", displayName: "Local Owner", token: bootstrapToken, permissions: ["household_admin"], protectedDomains: protectedProfileDomains, createdAt: now(), localOnly: true }); return profiles().get("owner"); }
export function createProfile({ displayName, permissions = [] }) { if (!displayName?.trim() || displayName.length > 80) throw Object.assign(new Error("A display name of 1–80 characters is required."), { status: 400 }); const profile = { id: id("profile"), displayName: displayName.trim(), token: crypto.randomUUID(), permissions: [...new Set(permissions)].filter((permission) => typeof permission === "string" && permission.length <= 80), protectedDomains: protectedProfileDomains, createdAt: now(), localOnly: true }; profiles().set(profile.id, profile); return profile; }
export function authenticate({ profileId, token }) { if (!profileId || !token) throw Object.assign(new Error("Authentication is required."), { status: 401 }); const profile = profiles().get(profileId); if (!profile || profile.token !== token) throw Object.assign(new Error("Invalid profile credential."), { status: 403 }); return profile; }
export function grantAccess({ from, to, domain, permissions = ["read"] }) { if (!profiles().has(from) || !profiles().has(to) || !protectedProfileDomains.includes(domain) || !Array.isArray(permissions)) throw Object.assign(new Error("A valid profile pair, domain, and permissions are required."), { status: 400 }); const grant = { id: id("grant"), from, to, domain, permissions: [...new Set(permissions)].filter((permission) => permission === "read" || permission === "write"), active: true, createdAt: now(), revokedAt: null, revokedBy: null }; grants().set(grant.id, grant); return grant; }
export function revokeGrant(requester, grantId, { householdAdmin=false, householdProfileIds=[] } = {}) { const grant = grants().get(grantId); if (!grant) return false; const scopedAdmin=Boolean(householdAdmin&&householdProfileIds.includes(grant.from)); if (requester.id !== grant.from && requester.id !== grant.to && !scopedAdmin) throw Object.assign(new Error("You cannot revoke this grant."), { status: 403 }); grant.active = false; grant.revokedAt = now(); grant.revokedBy = requester.id; return true; }
export function mayAccessProfile({ requesterProfileId, targetProfileId, domain, permission = "read" }) { return requesterProfileId === targetProfileId || list("profile_grants", (grant) => grant.active && grant.from === targetProfileId && grant.to === requesterProfileId && grant.domain === domain && grant.permissions.includes(permission)).length > 0; }
export function recordAccess(entry) { const record = { id: id("access"), at: now(), ...entry }; audit().set(record.id, record); return record; }
export function accessAudit(profileId) { return list("access_audit", entry => entry.profileId === profileId); }
export function setWakeNicknames(profile, nicknames) { if (!Array.isArray(nicknames) || nicknames.length > 8 || !nicknames.every((name) => typeof name === "string" && name.trim().length >= 2 && name.trim().length <= 32)) throw Object.assign(new Error("Provide up to eight wake nicknames of 2–32 characters."), { status: 400 }); profile.wakeNicknames = [...new Set(nicknames.map((name) => name.trim().toLowerCase()))]; return profile; }
export function profileById(profileId) { return profiles().get(profileId) || null; }
export function profileSummary(profile) { const { token, ...safe } = profile; return safe; }
