import { id, list, now, table } from "../state/store.js";
export const integrationStates = ["available_now", "active_connection", "designed_not_connected", "requires_authorization", "revoked", "unavailable"];
export const adapterKinds = ["apple_siri_iphone", "amazon_alexa_echo", "google_nest", "smart_home", "vehicle", "tv", "wearable", "computer", "health_data", "pet_care", "emergency_contacts"];
const connections = () => table("integration_connections"); const audits = () => table("integration_audits");
export function adapterContract(kind) { if (!adapterKinds.includes(kind)) throw new Error("That integration adapter is not registered."); return { kind, state: "designed_not_connected", authorization: "official_api_and_explicit_scoped_consent_required", leastPrivilege: true, methods: ["authorize", "revoke", "audit"], externalConnection: false }; }
export function requestConnection(profileId, kind, permissions = []) { const contract = adapterContract(kind); const connection = { id: id("integration"), profileId, kind, requestedPermissions: [...new Set(permissions)], grantedPermissions: [], state: "requires_authorization", createdAt: now(), revokedAt: null }; connections().set(connection.id, connection); audit(profileId, connection.id, "authorization_requested"); return { ...connection, contract }; }
export function authorizeConnection(profileId, connectionId, grantedPermissions = []) { const item = connections().get(connectionId); if (!item || item.profileId !== profileId) throw new Error("Integration request not found."); if (item.state === "revoked") throw new Error("A revoked integration cannot be authorized."); item.grantedPermissions = grantedPermissions.filter((scope) => item.requestedPermissions.includes(scope)); item.state = "requires_authorization"; item.authorizedAt = now(); audit(profileId, item.id, "authorization_recorded_provider_not_connected"); return item; }
export function revokeConnection(profileId, connectionId) { const item = connections().get(connectionId); if (!item || item.profileId !== profileId) return false; item.state = "revoked"; item.revokedAt = now(); audit(profileId, item.id, "revoked"); return true; }
export function integrationStatus(profileId) { return adapterKinds.map((kind) => ({ ...adapterContract(kind), connection: list("integration_connections", (item) => item.profileId === profileId && item.kind === kind).at(-1) || null })); }
export function audit(profileId, connectionId, action) { const entry = { id: id("integration_audit"), profileId, connectionId, action, at: now() }; audits().set(entry.id, entry); return entry; }
export function integrationAudit(profileId) { return profileId ? list("integration_audits", (entry) => entry.profileId === profileId) : list("integration_audits"); }
