import { id, list, now, table } from "../state/store.js";
export const worldEntityTypes = ["person","relationship","home","room","device","smart_home","vehicle","pet","environment","schedule","project","work","purchase","subscription","package","document","research","music","education","wellness","goal","opportunity","service","travel","security","external_system"];
export const knowledgeStates = ["known","unknown","inferred","stale","unavailable","verified","unverified","approximate","authorized","unauthorized"];
export const provenanceTypes = ["user","authorized_profile","authorized_device","authorized_sensor","official_external_source","public_source","connected_service","inference","unverified_claim"];
const facts=()=>table("world_facts");
const finiteConfidence=value=>Number.isFinite(Number(value))&&Number(value)>=0&&Number(value)<=1;
export function captureWorldFact(profileId,input){if(!worldEntityTypes.includes(input.entityType)||!input.subject?.trim()||input.subject.length>120||!input.key?.trim()||input.key.length>120||!provenanceTypes.includes(input.provenance)||!finiteConfidence(input.confidence))throw Object.assign(new Error("World fact type, subject, key, provenance, and confidence are required."),{status:400});if(input.authorized!==true)throw Object.assign(new Error("World facts require explicit authorization."),{status:403});const ttl=Number(input.ttlHours??168);if(!Number.isFinite(ttl)||ttl<1||ttl>8760)throw Object.assign(new Error("World fact retention must be 1–8760 hours."),{status:400});const createdAt=now();const observedAt=input.observedAt||createdAt;const observedTime=new Date(observedAt).getTime();if(!Number.isFinite(observedTime)||observedTime>Date.now()+60000)throw Object.assign(new Error("World fact observation time is invalid."),{status:400});const fact={id:id("fact"),profileId,entityType:input.entityType,subject:input.subject.trim(),key:input.key.trim(),value:input.value,provenance:input.provenance,confidence:Number(input.confidence),certainty:input.confidence>=.9?"certain":input.confidence>=.7?"strong":input.confidence>=.4?"weak":"unknown",verification:input.verified===true?"verified":input.provenance==="inference"?"inferred":"unverified",authorization:"authorized",observedAt,createdAt,updatedAt:createdAt,expiresAt:new Date(observedTime+ttl*3600000).toISOString()};facts().set(fact.id,fact);return fact;}
export function worldFacts(profileId,{entityType,includeStale=false}={}){const time=Date.now();return list("world_facts",fact=>fact.profileId===profileId&&(!entityType||fact.entityType===entityType)).map(fact=>({...fact,state:new Date(fact.expiresAt).getTime()<=time?"stale":fact.verification})).filter(fact=>includeStale||fact.state!=="stale");}
export function worldSummary(profileId){const all=worldFacts(profileId,{includeStale:true});return{total:all.length,verified:all.filter(x=>x.state==="verified").length,inferred:all.filter(x=>x.state==="inferred").length,stale:all.filter(x=>x.state==="stale").length,uncertain:all.filter(x=>x.certainty==="weak"||x.certainty==="unknown").length,byType:Object.fromEntries(worldEntityTypes.map(type=>[type,all.filter(x=>x.entityType===type).length]))};}
export function changedSince(profileId,since){const timestamp=new Date(since).getTime();if(!Number.isFinite(timestamp))throw Object.assign(new Error("A valid since timestamp is required."),{status:400});return worldFacts(profileId,{includeStale:true}).filter(fact=>new Date(fact.updatedAt).getTime()>timestamp);}
